# Generated by Django 5.2.6 on 2025-10-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('clave_emp', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Clave de Empleado')),
                ('nombre_emp', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido_emp', models.CharField(max_length=100, verbose_name='Apellido')),
                ('puesto_emp', models.CharField(max_length=100, verbose_name='Puesto')),
                ('fecha_contratacion', models.DateField(verbose_name='Fecha de Contratación')),
                ('activo_emp', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'Empleado',
            },
        ),
    ]
